steps:
  - id: 'lighthouse'
    name: cypress/browsers:node14.15.0-chrome86-ff82
    entrypoint: '/bin/sh'
    args: ['-c', 'npm install -g @lhci/cli@0.7.x && lhci autorun --failOnUploadFailure']
    env:
      - 'LHCI_BUILD_CONTEXT__CURRENT_BRANCH=$BRANCH_NAME'

options:
  machineType: 'UNSPECIFIED'