steps:
  - id: 'lighthouse'
    name: zenika/alpine-chrome:89-with-node-14
    entrypoint: '/bin/sh'
    args: ['-c', 'chown -R 1000:1000 "/builder/home/.npm" && npm install -g @lhci/cli@0.7.x && lhci autorun --failOnUploadFailure']
    env:
      - 'LHCI_BUILD_CONTEXT__CURRENT_BRANCH=$BRANCH_NAME'

options:
  machineType: 'UNSPECIFIED'