steps:
  - id: 'lighthouse'
    name: patrickhulce/lhci-client:latest
    entrypoint: '/bin/sh'
    args: ['-c', 'lhci autorun --failOnUploadFailure']
    env:
      - 'LHCI_BUILD_CONTEXT__CURRENT_BRANCH=$BRANCH_NAME'

options:
  machineType: 'UNSPECIFIED'